language: node_js

sudo: false

cache:
  directories:
    - node_modules
    - bower_components
    - vendor

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember test